#!/usr/bin/env node
/*
 * gen-config.mjs — build-time config injector (v0.6)
 * -------------------------------------------------------------------------
 * Overwrites ./config.js with values from environment variables so the real
 * Google Maps key + historian/API endpoints + auth token are NEVER committed
 * to source. Run as the Vercel build step:
 *
 *   "buildCommand": "node scripts/gen-config.mjs"
 *
 * Required (set by Ops as Vercel/GitHub secrets):
 *   GOOGLE_MAPS_API_KEY_WEB   referrer-restricted browser key (Alex's dev key)
 * Optional (data layer; app degrades to seed/cache if unset):
 *   HISTORIAN_URL, API_FALLBACK_URL, AUTH_TOKEN, POLL_MS, STALE_MS
 *
 * Safe to run locally: with no env vars set it regenerates the same safe
 * placeholders that are checked into git.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const env = process.env;

const cfg = {
  HISTORIAN_URL: env.HISTORIAN_URL || "",
  API_FALLBACK_URL: env.API_FALLBACK_URL || "",
  AUTH_TOKEN: env.AUTH_TOKEN || "",
  GOOGLE_MAPS_API_KEY_WEB: env.GOOGLE_MAPS_API_KEY_WEB || "",
  MAP_CENTER: { lat: 46.8065, lng: -71.2451 },
  MAP_ZOOM: 12,
  POLL_MS: Number(env.POLL_MS) || 60000,
  STALE_MS: Number(env.STALE_MS) || 180000
};

const banner =
  "/* GENERATED by scripts/gen-config.mjs at build time — DO NOT EDIT.\n" +
  "   Values come from environment variables; secrets are never committed. */\n";

const body =
  banner +
  "window.APP_CONFIG = Object.assign(" +
  JSON.stringify(cfg, null, 2) +
  ", window.APP_CONFIG || {});\n";

const out = join(ROOT, "config.js");
writeFileSync(out, body, "utf8");

const keyState = cfg.GOOGLE_MAPS_API_KEY_WEB ? "SET" : "MISSING (map will show 'key not configured')";
const histState = cfg.HISTORIAN_URL ? "SET" : "unset (seed/cache fallback)";
console.log(`[gen-config] wrote ${out}`);
console.log(`[gen-config]   GOOGLE_MAPS_API_KEY_WEB: ${keyState}`);
console.log(`[gen-config]   HISTORIAN_URL: ${histState}`);
console.log(`[gen-config]   API_FALLBACK_URL: ${cfg.API_FALLBACK_URL ? "SET" : "unset"}`);
